replicaCount: 1

fullnameOverride: ""
nameOverride: ""

image:
  repository: registry
  tag: "2.8.3"
  pullPolicy: IfNotPresent

serviceAccount:
  name: ""

service:
  type: ClusterIP
  port: 5000

metrics:
  enabled: true
  port: 5001

tls:
  enabled: false
  secretName: ""
  autoGenerate: true
  commonName: "registry.paap.local"

ingress:
  enabled: true
  className: ""
  host: "registry.paap.local"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

persistence:
  enabled: true
  size: 5Gi

deleteEnabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

paap:
  toolNamespace: ""
  primaryNamespace: ""
  environment: ""
