server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    gzip on;
    gzip_min_length 1k;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    __TEMPLATE__FOR__LOCATION_LIST__Location 规则__
    location __TEMPLATE__ITEM_MATCH__匹配规则__DEFAULT__/__ {
        __TEMPLATE__ITEM_DIRECTIVES__指令块__
    }
    __TEMPLATE__END__LOCATION_LIST__
}
