serviceAccount:
  create: false
rbac:
  create: false
networkPolicy:
  enabled: false
persistence:
  enabled: false
cluster:
  init: true
  nodes: 6
  replicas: 1
usePassword: true
usePasswordFiles: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
