apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ ternary "https" "http" .Values.tls.enabled }}
      port: {{ .Values.service.port }}
      targetPort: {{ ternary "https" "http" .Values.tls.enabled }}
