server {
    listen 80;
    server_name __TEMPLATE__SERVER_NAME__访问域名__DEFAULT__example.com__;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name __TEMPLATE__SERVER_NAME__访问域名__DEFAULT__example.com__;

    ssl_certificate __TEMPLATE__SSL_CERTIFICATE__证书路径__DEFAULT__/etc/nginx/certs/fullchain.pem__;
    ssl_certificate_key __TEMPLATE__SSL_CERTIFICATE_KEY__证书私钥路径__DEFAULT__/etc/nginx/certs/privkey.pem__;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    __TEMPLATE__FOR__LOCATION_LIST__Location 规则__
    location __TEMPLATE__ITEM_MATCH__匹配规则__DEFAULT__/__ {
        __TEMPLATE__ITEM_DIRECTIVES__指令块__
    }
    __TEMPLATE__END__LOCATION_LIST__
}
