user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        __TEMPLATE__FOR__LOCATION_LIST__Location 规则__
        location __TEMPLATE__ITEM_MATCH__匹配规则__DEFAULT__/__ {
            __TEMPLATE__ITEM_DIRECTIVES__指令块__
        }
        __TEMPLATE__END__LOCATION_LIST__
    }
}
