FROM golang:1.26-alpine AS builder
WORKDIR /workspace
ENV GOPROXY=https://goproxy.cn,direct
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o paap-operator cmd/operator/main.go

FROM alpine:3.22
WORKDIR /
COPY --from=builder /workspace/paap-operator /paap-operator
RUN apk add --no-cache ca-certificates
USER 65532:65532
ENTRYPOINT ["/paap-operator"]
