package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ServiceInstanceSpec defines the desired state of ServiceInstance
type ServiceInstanceSpec struct {
	// 关联的环境（同 namespace 下的 Environment CR 名）
	EnvironmentRef ObjectReference `json:"environmentRef"`

	// 服务类型：deploy / ci / monitor / postgresql / redis / ...
	Type string `json:"type"`

	// 工具独占的 namespace（{app}-{env}-{tool}）
	ToolNamespace string `json:"toolNamespace"`

	// 用户提交的参数
	// +optional
	Parameters map[string]string `json:"parameters,omitempty"`

	// SA 配置（自动生成，namespace 为 ToolNamespace）
	ServiceAccount ServiceAccountSpec `json:"serviceAccount"`

	// 工具在自己 namespace 内需要的权限（如访问 CRD）
	// +optional
	ToolNamespaceRole *RoleSpec `json:"toolNamespaceRole,omitempty"`

	// 工具需要的集群级只读权限（例如 ArgoCD/Prometheus 的 discovery/cache）
	// +optional
	ClusterRole *RoleSpec `json:"clusterRole,omitempty"`

	// 工具需要对负载 namespace 的操作权限
	WorkloadRole RoleSpec `json:"workloadRole"`

	// 工具需要对同环境内其它 namespace 的操作权限（工具/中间件/数据库等）
	// +optional
	EnvironmentRole *RoleSpec `json:"environmentRole,omitempty"`

	// 渲染后的部署清单（存储在 ConfigMap 中）
	// +optional
	ManifestsRef *ConfigMapReference `json:"manifestsRef,omitempty"`

	// Helm chart installation managed by the operator.
	// +optional
	Helm *HelmInstallSpec `json:"helm,omitempty"`
}

type ObjectReference struct {
	Name string `json:"name"`
}

type ServiceAccountSpec struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type RoleSpec struct {
	Rules []PolicyRule `json:"rules"`
}

type PolicyRule struct {
	APIGroups []string `json:"apiGroups"`
	Resources []string `json:"resources"`
	Verbs     []string `json:"verbs"`
}

type ConfigMapReference struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type HelmInstallSpec struct {
	ReleaseName      string            `json:"releaseName"`
	Namespace        string            `json:"namespace"`
	ChartRepo        string            `json:"chartRepo,omitempty"`
	ChartName        string            `json:"chartName,omitempty"`
	ChartVersion     string            `json:"chartVersion,omitempty"`
	ChartArchivePath string            `json:"chartArchivePath,omitempty"`
	S3Bucket         string            `json:"s3Bucket,omitempty"`
	S3Key            string            `json:"s3Key,omitempty"`
	PresetValues     string            `json:"presetValues,omitempty"`
	PlatformManifest string            `json:"platformManifest,omitempty"`
	Values           map[string]string `json:"values,omitempty"`
}

// ServiceInstanceStatus defines the observed state of ServiceInstance
type ServiceInstanceStatus struct {
	// Phase: Pending / Installing / Running / Upgrading / Deleting / Error
	Phase string `json:"phase,omitempty"`

	// SA 状态
	ServiceAccount *ServiceAccountStatus `json:"serviceAccount,omitempty"`

	// RBAC 覆盖的 namespace 列表
	RBACNamespaces []RBACNamespaceStatus `json:"rbacNamespaces,omitempty"`

	// 工具组件状态
	Components []ToolComponentStatus `json:"components,omitempty"`

	// 条件
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// 观察到的 generation
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

type ServiceAccountStatus struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Created   bool   `json:"created"`
}

type RBACNamespaceStatus struct {
	Namespace          string `json:"namespace"`
	RoleCreated        bool   `json:"roleCreated"`
	RoleBindingCreated bool   `json:"roleBindingCreated"`
}

type ToolComponentStatus struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Ready    bool   `json:"ready"`
	Replicas string `json:"replicas"`
	Reason   string `json:"reason,omitempty"`
	Message  string `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Type",type=string,JSONPath=`.spec.type`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// ServiceInstance is the Schema for the serviceinstances API
type ServiceInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceInstanceSpec   `json:"spec,omitempty"`
	Status ServiceInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceInstanceList contains a list of ServiceInstance
type ServiceInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceInstance `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ServiceInstance{}, &ServiceInstanceList{})
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ServiceInstance) DeepCopyInto(out *ServiceInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function
func (in *ServiceInstance) DeepCopy() *ServiceInstance {
	if in == nil {
		return nil
	}
	out := new(ServiceInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function
func (in *ServiceInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceInstanceSpec) DeepCopyInto(out *ServiceInstanceSpec) {
	*out = *in
	out.EnvironmentRef = in.EnvironmentRef
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ServiceAccount = in.ServiceAccount
	if in.ToolNamespaceRole != nil {
		in, out := &in.ToolNamespaceRole, &out.ToolNamespaceRole
		*out = new(RoleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRole != nil {
		in, out := &in.ClusterRole, &out.ClusterRole
		*out = new(RoleSpec)
		(*in).DeepCopyInto(*out)
	}
	in.WorkloadRole.DeepCopyInto(&out.WorkloadRole)
	if in.EnvironmentRole != nil {
		in, out := &in.EnvironmentRole, &out.EnvironmentRole
		*out = new(RoleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ManifestsRef != nil {
		in, out := &in.ManifestsRef, &out.ManifestsRef
		*out = new(ConfigMapReference)
		**out = **in
	}
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmInstallSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ServiceInstanceSpec) DeepCopy() *ServiceInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceInstanceStatus) DeepCopyInto(out *ServiceInstanceStatus) {
	*out = *in
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccountStatus)
		**out = **in
	}
	if in.RBACNamespaces != nil {
		in, out := &in.RBACNamespaces, &out.RBACNamespaces
		*out = make([]RBACNamespaceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ToolComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ServiceInstanceStatus) DeepCopy() *ServiceInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HelmInstallSpec) DeepCopyInto(out *HelmInstallSpec) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *HelmInstallSpec) DeepCopy() *HelmInstallSpec {
	if in == nil {
		return nil
	}
	out := new(HelmInstallSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}
