apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
    - name: ssh
      port: {{ .Values.service.ssh.port }}
      targetPort: ssh
