apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gitea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
    - name: ssh
      port: {{ .Values.service.ssh.port }}
      targetPort: ssh
