# 禁用内置 RBAC，由平台统一管理
controller:
  imagePullPolicy: IfNotPresent
  rbac:
    create: false
  serviceAccount:
    create: false
  adminPassword: "admin123"
  serviceType: NodePort
  javaOpts: "-Xms256m -Xmx1024m"
  installLatestPlugins: false
  installLatestSpecifiedPlugins: false
  metrics:
    enabled: true

serviceAccount:
  create: false

rbac:
  create: false

persistence:
  enabled: false
