server {
    listen 80;
    server_name _;

    __TEMPLATE__FOR__LOCATION_LIST__Location 规则__
    location __TEMPLATE__ITEM_MATCH__匹配规则__DEFAULT__~* \.(jpg|jpeg|png|gif|ico|css|js)$__ {
        __TEMPLATE__ITEM_DIRECTIVES__指令块__
    }
    __TEMPLATE__END__LOCATION_LIST__
}
